Category.create!([
  {name: "Thông tin - Sự kiện", description: "Khu vực thảo luận về thông tin và các sự kiện về công nghệ"},
  {name: "Máy tính", description: "Thảo luận các loại máy tính, laptop, pc, macbook sử dụng các loại hệ điều hành Windows, Linux, Chrome OS, Mac OS X"},
  {name: "Điện thoại", description: "Khu vực thảo luận về các loại điện thoại, điện thoại thông minh và máy tính bảng sử dụng các loại hệ điều hành iOS, Android, Windows Phone, Blackberry, Palm, Linux, Symbian,..."},
  {name: "Camera", description: "Diễn đàn thảo luận Camera, Máy ảnh số, Máy quay phim, nhiếp ảnh, kỹ thuật và nghệ chụp ảnh đẹp, gửi ảnh, bình ảnh, giao lưu, offline."},
  {name: "Hỗ trợ", description: "Các khu vực hỗ trợ thành viên"}
])
Comment.create!([
  {content: "First comment 30 charrrrrrrrrr", user_id: 2, topic_id: 3},
  {content: "Second comment 30 charrrrrrrrr", user_id: 2, topic_id: 3},
  {content: "Khong co iphone 30 charrrrrrrrrrrr", user_id: 2, topic_id: 7}
])
Information.create!([
  {sex: "Male", birth: "1996-07-13", phone: "01639530113", address: "VN", introduce: "Yêu màu tím và ghét sự thủy chung", user_id: 1, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {sex: "Male", birth: "1998-05-10", phone: "54861823185", address: "JP", introduce: "", user_id: 2, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil}
])
Topic.create!([
  {title: "NVIDIA chính thức giới thiệu GTX 1080 hiệu năng mạnh nhất thế giới, giá từ 13 triệu", content: "Sáng nay 7.5, tại sự kiện đặc biệt của mình NVIDIA đã công bố thế hệ card màn hình mới với cấu trúc Pascal dành cho người dùng phổ thông mang tên gọi, Geforce GTX 1080. Theo giám đốc điều hành (CEO) của NIVDIA, ông Jen-Hsun Huang, GTX 1080 nhanh hơn 2 card GTX 980 (600 USD) chạy song song, và thậm chí lật đổ 'ngai vàng' của card màn hình mạnh nhất hiện nay, Titan X (giá 1000 USD). Sở hữu cấu trúc mới Pascal tương tự như P100 trước đó, GTX 1080 được sản xuất dựa trên công nghệ 16nm FinFET (bóng dẫn 3 chiều), mang lại hiệu năng và tốc độ cực khủng.", user_id: 1, category_id: 1},
  {title: "Giải pháp thông minh quản lý khách sạn, nhà nghỉ, spa, resort, karaoke, nhà hàng,...", content: "* Các giải pháp thường triển khai\r\n+ Dùng sổ ghi chép: Nhân viên tự tính giá tiền.\r\n+ Dùng phần mềm: Tự động tính được giá phòng.\r\nTất cả giải pháp trên đều có sự thất thoát về tiền phòng nếu nhân viên không cập nhật phần mềm hay ghi chép vào sổ. Lãng phí về tiêu thụ điện do không có hệ thống tự động bật tắt điện khi có khách nghỉ.\r\n* Giải pháp hệ thống điều khiển thiết bị điện EziBee\r\nTự động hóa hoàn toàn:\r\n1) Buộc lễ tân check in cho khách (sau khi check in -> điện trong phòng mới kích hoạt)\r\n2) Buộc lễ tân phải check out cho khách (nếu không hệ thống tiếp tục tính tiền)\r\n3) Nguồn điện được sử dụng một cách tối đa nhất (Chỉ khi phòng có khách nguồn điện mới kích hoạt)\r\n4) Giám sát hoạt động kinh doanh online 24/24 qua điện thoại, máy tính bảng\r\nHệ thống quản lý thông minh, dễ dàng sử dụng, tránh thất thoát tiền phòng, tiết kiệm điện..", user_id: 1, category_id: 1},
  {title: "Thiên tài bị lãng quên: Năm 1957, ông tạo ra chiếc máy VR đầu tiên", content: "Gió, mùi hương, độ rung - những hiệu ứng này, sớm đã có trên chiếc Sensorama của Morton Heilig vào năm 1957, đáng tiếc rằng nó đã không thành công trong việc thương mại.\r\nCó thể bạn nghĩ thực tế ảo có từ những năm 1980, từ những bộ phim khoa học viễn tưởng hay những sản phẩm thử nghiệm thời đó. Nhưng, bạn có thể không biết rằng, sản phẩm VR có thể sử dụng đầu tiên trên thế giới đã có từ năm 1957, và vẫn hoạt động cho đến tận hôm nay.\r\n\r\nNếu chỉ gọi Morton Heilig là một người nhìn xa trông rộng sẽ là đánh giá quá thấp tài năng của ông. Khi đa phần mọi người vẫn còn đang sử dụng tivi trắng đen, ông đã chế tạo thành công chiếc máy video 3D đầy đủ chức năng cho phép bạn lái một chiếc xe mô tô ảo trên đường với âm thanh, gió thổi, rung lắc và thậm chí là mùi hương.\r\n\r\nÔng gọi nó là Sensorama Simulator, nhưng nó đã thất bại một cách thảm hại.\r\n\r\nTuy Sensorama Simulator là một sản phẩm tiên phong, nhưng trong thời gian dài chẳng ai chú ý đến nó. Ông và vợ ông - Marianne đã cùng nhau tạo nên nhiều phát minh, vì để trợ giúp cho nghiên cứu của chồng, bà đã phải chịu rất nhiều khoản nợ nần, cho đến khi chồng bà qua đời gần hai thập kỷ, khoản nợ vẫn chưa trả xong.\r\n\r\nKhi bà nhận lời phỏng vấn của trang công nghệ Techradar, bà nói: \"Anh ấy gọi mình là Renaissance Man (người phục hưng), bởi anh ấy có rất nhiều tài năng khác nhau. Khi lần đầu anh ấy đưa tôi đến căn hộ nơi có chiếc máy, tôi đã rất kinh ngạc, nhưng khi ấy tôi không hiểu được tầm quan trọng của nó\". \r\n\r\nBà không phải là người duy nhất.\r\n\r\nLà một nhà quay phim tài năng, Heilig tạo ra Sensorama với mong muốn xây dựng \"tương lai của điện ảnh\". Thế nhưng rạp chiếu phim 3D thì cần có những bộ phim 3D, một thứ không phải dễ dàng kiếm được vào cuối những năm 1950.", user_id: 1, category_id: 1},
  {title: "NVIDIA ra mắt siêu máy tính nhỏ như một cái thùng máy desktop, dùng cho trí tuệ nhân tạo", content: "NVIDIA vừa giới thiệu DGX-1, một siêu máy tính có kích thước chỉ chỉ to hơn chút xíu so với một cái thùng máy desktop nhưng lại chứa sức mạnh của 250 server lẻ cộng lại. Để làm được điều này, DGX-1 sử dụng 2 CPU Intel Xeon-E5 2697 v3, kèm theo đó là 8 card đồ họa NVIDIA Tesla P100 dựa trên kiến trúc Pascal mới. Đây là GPU nhanh nhất từng được NVIDIA làm và nó không chỉ tốt cho tác vụ đồ họa mà còn giúp được cho các công việc đòi hỏi sức mạnh tính toán lớn. Một chiếc DGX-1 có hiệu năng dấu chấm động là 170 teraflops, nếu ghép nhiều máy lại thì có thể lên tới con số 2 petaflops. Để bạn dễ so sánh thì chiếc siêu máy tính mạnh nhất thế giới hiệu tại có sức xử lý 10 petaflops.\r\n\r\nDGX-1 sẽ được dùng cho những tác vụ huấn luyện trí tuệ nhân tạo, chẳng hạn như luyện cho hệ thống thông minh biết cách lái xe an toàn, biết hình ảnh nào là vật thể gì, biết cách tự nhận biết một số thao tác của con người để mà tránh né... NVIDIA gợi ý rằng xe tự hành hay robot có thể xác định được vật thể và đường đi bằng cách thu thập hình ảnh rồi tiến hành so sánh với một số lượng cực lớn dữ liệu tham chiếu chứa trên những hệ thống đám mây chạy DGX-1.\r\n\r\nNVIDIA chưa công bố giá của DGX-1 nhưng chắc chắn là sẽ không rẻ.", user_id: 1, category_id: 2},
  {title: "Tìm kiếm nhanh và tiện hơn trong Windows 10", content: "Tìm kiếm là việc mà chắc chắn ai cũng phải thực hiện trên máy tính vì không phải lúc nào chúng ta cũng nhớ chính xác file của mình đang nằm ở đâu. Cũng có khi chúng ta dùng search đơn giản vì nó sẽ giúp chúng ta mở file nhanh hơn so với việc phải đi qua nhiều lớp folder. Trong Windows 10, mình có vài mẹo nhỏ liên quan đến tìm kiếm muốn chia sẻ với anh em, từ việc search nhanh bằng chữ cái đầu tiên, gắn search lên taskbar cho đến các toán tử tìm kiếm nâng cao. ", user_id: 1, category_id: 2},
  {title: "Trên tay bàn phím Apple cho iPad Pro: bấm ngon, linh hoạt, giá cao...", content: "iPad Pro vần một chiếc bàn phím, một chiếc nắp để bảo vệ và một chiếc đế để đứng. Và Apple làm ra một phụ kiện 3 trong một đó. Bạn sẽ rất thích chiếc bàn phím này của Apple vì cảm giác bấm tuyệt vời của nó. Tiếp theo bạn sẽ thích vì nó gọn, nhẹ và cực kỳ linh hoạt. Cám cơn cổng kết nối mới (smart connector) của Apple giúp không chỉ kết nối mà còn truyền tải được cả điện nên chúng ta không cần pin dưới bàn phím.\r\n\r\nGiá có lẽ là yếu điểm lớn nhất của chiếc bàn phím này, Apple liên tục hoãn giao hàng nên giá gốc (thị trường Mỹ) vốn đã cao 169usd(chưa thuế, chưa ship) về đến Việt Nam lại còn cao hơn với giá chào bán từ 6 triệu trở lên.", user_id: 1, category_id: 3},
  {title: "Người dùng khắp nơi hoảng hốt vì iphone 6s, plus bị tróc lỡ, sùi rỉ", content: "Chắc vì để thu lãi nhiều thật nhiều nên apple dùng lớp mạ rẻ tiền cho tiết kiệm. \r\nLúc đầu chỉ tưởng hiện tượng này ở Việt Nam, nhưng bây giờ đã xuất hiện ở các nước châu Á, Châu Âu và cả ở Mỹ.\r\nHiện tượng sùi rỉ trên tất cả các màu gold, bạc và vàng hồng. Người dùng đem đi bảo hành nhưng không được đổi máy mới. Apple vẫn chưa lên tiếng về việc này.", user_id: 2, category_id: 3}
])
User.create!([
  {name: "Trần Trung Kiên", email: "kientt13.7@gmail.com", password_digest: "$2a$10$q8XSnEUpsihBKWwVRwBES.h5EE/b4VUI9b7rFKuV/fb3z3f7A47hS", remember_digest: nil},
  {name: "Edogawa Conan", email: "conan@gmail.com", password_digest: "$2a$10$/u7.ZOD78jAYihsVq7DucePdW8p/XrXaPKHXH9EXTbXmF5xIqN066", remember_digest: nil}
])
